### PR TITLE
PR to add Reward info to Insight Explorer

### PR DESCRIPTION
**Pull request by gaeacodes**
This PR just contains the changes needed for the UI.
I have submitted other PR's to @DeckerSU's bitcore-node-komodo(https://github.com/DeckerSU/bitcore-node-komodo/pull/2), insight-api-komodo(https://github.com/DeckerSU/insight-api-komodo/pull/1) 

When merged, all of these together will allow reward data to be displayed on the insight explorer.
To test my changes, scripts in the repo https://github.com/gaeacodes/komodo-install-explorer can be used

Make sure `komodod` is not running and execute the following commands:

```
git clone https://github.com/gaeacodes/komodo-install-explorer
cd komodo-install-explorer
./setup-explorer-directory.sh
./install-komodo-explorer.sh
./komodo-explorer-start.sh
```

Then, start `komodod` with all the indexes like tx,timestamp,spent and address enabled and visit http://localhost:7774 to view the explorer.

Thanks to @gcharang for all the suggestions and help.

The Insight API gets a few addtions to the `tx` endpoint. To view them, visit `http://localhost:7774/insight-api-komodo/tx/<txid>`

Here are a few screenshots that show the addtions done to UI.

Screenshot from 2021-01-23 19-30-21
Screenshot from 2021-01-23 19-31-20
Screenshot from 2021-01-23 19-33-37
Screenshot from 2021-01-23 19-52-01
Screenshot from 2021-01-23 19-52-11

### CODE REVIEW

**Comment by ca333** [comment]
screenshots look great - will review and test patch tomorrow, thank you @gaeacodes !

**Comment by smk762** [comment]
I'm reindexing for addresindex etc, should be able to test tonight.

**Comment by smk762** [comment]
Text alignment still looks a bit high, buttons have disappeared!
image

**Comment by gaeacodes** [comment]
>Distinquished all needed changes from 3 repoes (bitcore-node-komodo, insight-api-komodo, insight-ui-komodo) as a patches, made an instruction, all of these already available in commit above. Live demo available here - api.kmd.dev and here - explorer.kmd.sh


From DeckerSU as a [comment](https://github.com/DeckerSU/bitcore-node-komodo/pull/2#issuecomment-766801080) to the PR for bitcore-node-komodo.

I have also hosted an updated instance of the explorer at http://34.122.103.103:7774

**Comment by smk762** [comment]
I'm still reindexing - slower than a wet sheep going uphill.
Tried to use a bootstrap but it errored so doing from scratch, about 50% there.

**Comment by smk762** [comment]
Looking good here, really nice additions!

I'm assuming the `KMD Available to Claim` is for individual utxos? As for the same address, some older tx are zero etc. most recent utxo having a value if matured.

Is it possible to add sum of pending rewards on address page in this section?
image

**Comment by gaeacodes** [comment]
>Looking good here, really nice additions!

thanks!

>I'm assuming the KMD Available to Claim is for individual utxos? 

"KMD Available to Claim" is for individual addresses.All the utxos of a single address are already combined for that element, so the value displayed and reward available to claim are for all the utxos belonging to the single address.

>As for the same address, some older tx are zero etc. most recent utxo having a value if matured.

If a utxo is spent we are setting reward to be claimed as 0.
Did you see any older tx that still has to be spent(also have reward to be spend),but the reward is 0?

>Is it possible to add sum of pending rewards on address page in this section?

It should be possible.will try!

**Comment by smk762** [comment]
> Did you see any older tx that still has to be spent(also have reward to be spend),but the reward is 0?

I don't believe so, but it was potentially a little confusing seeing same address in some cases having a 0 value, but in others having a non 0 value. Perhaps we should mark the relevant ones as "Rewards: N/A, utxo spent"?

Is there a threshold value for rewards display? I've been comparing rewards value to what is shown in AtomicDEX desktop and noticed a slight difference - have been waiting for some to accrue again to confirm. Example below.

image

**Comment by gaeacodes** [comment]
>I don't believe so, but it was potentially a little confusing seeing same address in some cases having a 0 value, but in others having a non 0 value. Perhaps we should mark the relevant ones as "Rewards: N/A, utxo spent"?

Will look into it

>Is there a threshold value for rewards display? I've been comparing rewards value to what is shown in AtomicDEX desktop and noticed a slight difference - have been waiting for some to accrue again to confirm. Example below.

Will check this too. but, did you refreshed the explorer page just before comparing with atomicdex?
the explorer page doesn't auto update.

**Comment by DeckerSU** [comment]
My 5 cents: to don't get users confused with `KMD Available to Claim: 0` caption, my offer is to change it on `Rewards Available` and show it only in case if rewards is non-zero, like below.

Before:
```
<b>KMD Available to Claim:</b> {{vout.totalAvailableRewards}}
```
After:
```
<span class="text-muted" data-ng-show="vout.totalAvailableRewards">Rewards Available: {{vout.totalAvailableRewards}} KMD</span>
```
It's already done on https://explorer.kmd.sh/ instance, so you can see "live-demo".

**Comment by smk762** [comment]
yep, fresh reload. Noticed a difference in values last night with another address 
- Explorer said 1.2530505
- AtomicDEX desktop said 1.26461712

After claiming
- old explorer said `FEE: -1.26460712 KMD`
- new explorer said `FEE: 0.02507101 KMD | REWARD: 1.28967813 KMD` (reward - fee = 1.26460712)

Might be due to calculation hours being offset by server/client timezone? FWIW my server is set to UTC time, PC is at GMT+8

**Comment by gaeacodes** [comment]
> yep, fresh reload. Noticed a difference in values last night with another address

Do you remember the address and transaction id by any chance?

**Comment by gaeacodes** [comment]
@smk762 I wasn't updating the tipTime after the initial start of the explorer.So, most of the calculations were wrong.
Can you please reinstall and test the explorer again?

**Comment by smk762** [comment]
not sure why, but if I try and restart komodod on the server I'm testing this with, every time it gives me
```
 Error opening block database.

error in HDD data, might just need to update to latest, if that doesnt work, then you need to resync
```

So, I'm reindexing again... then will check.

**Comment by smk762** [comment]
Still seeing a slight discrepancy between AtomicDEX pending rewards value and the explorer.
Address: RUwodWWAabv3h2jSatVDSMT89cLkTMSutA
AtomicDEX: 0.057114
New Explorer:  0.0571235

Claim txid: f275bfb02ada50151aecd0ab53fe056168af48649ec7ede78ffc96db8c6d5554
Old Explorer: FEE: -0.05710400 KMD  (assuming standard KMD tx fee of 0.00001, this adds up)
New Explorer: FEE: 0.00003375 KMD | REWARD: 0.05713775 KMD  (reward - fee = 0.057104)

New explorer fee looks a bit off - this was for a single utxo so it should have been the standard 0.00001

Refreshing the new explorer txid page after a few confirmations returned 
`FEE: 0.0000385 KMD | REWARD: 0.0571425 KMD`
Will keep a closer eye on this next time I claim.

From CLI RPC, here is the tx info:
```
{
  "txid": "f275bfb02ada50151aecd0ab53fe056168af48649ec7ede78ffc96db8c6d5554",
  "overwintered": true,
  "version": 4,
  "versiongroupid": "892f2085",
  "locktime": 1612671005,
  "expiryheight": 0,
  "vin": [
    {
      "txid": "89d885ba710f91f7a13e7492120f92d1f79f1d96a15685e833b46d373eb9659f",
      "vout": 0,
      "scriptSig": {
        "asm": "304402202ea5383c8f9b79d9f25c72e7a9b9e90351e81c2aa428ca43a1f78ab3059114b702201b98d72451d5c228e1a515e4d9aa14e5a24e2031031e1ada3342e12ea28ca7ee[ALL] 02ae795cb5fc5da6cb591106329752dfa3bc9a560f9f26c11f0d5167cf9fea3bbe",
        "hex": "47304402202ea5383c8f9b79d9f25c72e7a9b9e90351e81c2aa428ca43a1f78ab3059114b702201b98d72451d5c228e1a515e4d9aa14e5a24e2031031e1ada3342e12ea28ca7ee012102ae795cb5fc5da6cb591106329752dfa3bc9a560f9f26c11f0d5167cf9fea3bbe"
      },
      "sequence": 4294967295
    }
  ],
  "vout": [
    {
      "value": 50.05710400,
      "interest": 0.00000000,
      "valueZat": 5005710400,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 d7b7df991a3aeaaa764aeb34e16391d2789319f4 OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a914d7b7df991a3aeaaa764aeb34e16391d2789319f488ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "RUwodWWAabv3h2jSatVDSMT89cLkTMSutA"
        ]
      }
    }
  ],
  "vjoinsplit": [
  ],
  "valueBalance": 0.00000000,
  "vShieldedSpend": [
  ],
  "vShieldedOutput": [
  ]
}
```

**Comment by gaeacodes** [comment]
> Still seeing a slight discrepancy between AtomicDEX pending rewards value and the explorer.

AtomicDEX gets data from electrum server,so its reward calc might be slightly in the past. I am already calculating time of unconfirmed transaction to be the tiptime.

> New explorer fee looks a bit off - this was for a single utxo so it should have been the standard 0.00001

If the user's wallet doesn't claim as much as it is allowed to,then the rest of the reward is "fee". Not sure if miners claim it or its burned.

> Refreshing the new explorer txid page after a few confirmations returned

I am using current time as Unconfirmed txn's  block time till it's confirmed and blocktime stamp is returned.So, there will be diff between reward amount claimed displayed for the same transaction while it is unconfirmed vs confirmed.

**Comment by smk762** [comment]
I tracked the differential over a few minutes/blocks.
Seems the difference value between explorer and atomicdex is always a multiple of `0.00000476` for the address with a 50.057104 KMD balance.

Refreshing claim calc in atomicdex, I noticed it changed only once a new block arrived.
Same in explorer, I noticed rewards value change once new block arrives.
So I assume both are aligned to tiptime.
I thought to compare to value at https://dexstats.info/rewards.php?address=RUwodWWAabv3h2jSatVDSMT89cLkTMSutA but this is rounded to 4 decimals so not the precision I was after!

Also noticed a couple of times the explorer value appeared to have a float precision error like `Rewards Available: 0.0021420000000000002 KMD`

I'm waiting for a larger balance address to acrue some rewards to see what it's differential multiplier is in comparison, but I think a good idea might be to 
- round the rewards value to 4 decimal places
- change "Rewards Available:" to "Estimated Rewards Available:"

Feels silly to quibble over dust, and this could account for the minor differences. To satisfy my insatiable curiosity, I'll check with the atomicdex devs about how they calculate it - could you pls link me to the line/file where it is calculated for the explorer?

**Comment by gaeacodes** [comment]
https://github.com/gaeacodes/bitcore-node-komodo/blob/dev/lib/services/get-komodo-rewards.js

Using the above module for reward calcs. (Taken from https://www.npmjs.com/package/get-komodo-rewards)

Actual calc of reward claimed is done here: https://github.com/gaeacodes/bitcore-node-komodo/blob/77dd6135602d2b9216e9defe4145e015c67845f9/lib/services/bitcoind.js#L2257

> round the rewards value to 4 decimal places
> change "Rewards Available:" to "Estimated Rewards Available:"

Will make these changes. also working on adding rewards available to the address view.

**Comment by gaeacodes** [comment]
@smk762  added rewards available to the address summary in address view,limited the reward value to 4 decimals.Please do a fresh install and test when you have time.

**Comment by gaeacodes** [comment]
http://34.122.103.103:7775/tx/3d5643c80ac4dcc8cb4900508e27abde001affc219cfd12930168a2155a4e2e0
Please take a look at this txn.The user had rewards available but didn't claim them.So, those rewards are being treated as FEE and the rewards are called "Rewards Claimed" in txn summary.I can change the text if needed.

cc: @smk762

**Comment by smk762** [comment]
Good pickup. Currently it appears to be an exhorbitant fee, perhaps a better display would be to recalculate the fee (as minus the rewards value), and tag the rewards as "Lost rewards", hyperlinked to info on why they didnt get the rewards like https://support.komodoplatform.com/support/solutions/articles/29000024428-komodo-5-active-user-reward-all-you-need-to-know

Rewards value looks ok compared to atomicdex for address RUwodWWAabv3h2jSatVDSMT89cLkTMSutA

I was getting a crash for address RCyANUW2H5985zk8p6NHJfPyNBXnTVzGDh though.

in ~/.komodo/debug.log
```
2021-02-12 05:49:05 ERROR: GetTransaction: OpenBlockFile failed
2021-02-12 05:49:05 Unable to open file /home/smk762/.komodo/blocks/blk00134.dat
2021-02-12 05:49:05 ERROR: GetTransaction: OpenBlockFile failed
2021-02-12 05:49:05 LevelDB read failure: IO error: /home/smk762/.komodo/blocks/index/457739.ldb: Too many open files
2021-02-12 05:49:05 IO error: /home/smk762/.komodo/blocks/index/457739.ldb: Too many open files
2021-02-12 05:49:05 Unable to open file /home/smk762/.komodo/blocks/blk00134.dat
2021-02-12 05:49:05 ERROR: GetTransaction: OpenBlockFile failed
2021-02-12 05:49:05 Unable to open file /home/smk762/.komodo/blocks/blk00134.dat
```

In stdout for explorer
```
[2021-02-12T06:00:49.340Z] info: ::ffff:101.185.133.23 web socket subscribe: sync
[2021-02-12T06:00:49.622Z] info: ::ffff:101.185.133.23 "GET /insight-api-komodo/peer" 304 - 0.649 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" 
[2021-02-12T06:00:49.760Z] info: ::ffff:101.185.133.23 "GET /insight-api-komodo/addr/RLVzC4tr9cNKvuw2z4m8KuMfZURwCehx55/?noTxList=1" 304 - 507.598 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" 
[2021-02-12T06:00:50.178Z] info: ::ffff:101.185.133.23 "GET /insight-api-komodo/txs?address=RLVzC4tr9cNKvuw2z4m8KuMfZURwCehx55&pageNum=0" 200 - 41.257 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" 
[2021-02-12T06:01:07.161Z] info: ::ffff:101.185.133.23 "GET /insight-api-komodo/block/RCyANUW2H5985zk8p6NHJfPyNBXnTVzGDh" 404 9 4.878 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" 
[2021-02-12T06:01:07.521Z] info: ::ffff:101.185.133.23 "GET /insight-api-komodo/tx/RCyANUW2H5985zk8p6NHJfPyNBXnTVzGDh" 400 90 5.141 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" 
[2021-02-12T06:01:08.169Z] info: ::ffff:101.185.133.23 "GET /insight-api-komodo/addr/RCyANUW2H5985zk8p6NHJfPyNBXnTVzGDh/?noTxList=1" 400 53 293.231 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36" 
[2021-02-12T06:01:08.170Z] error: uncaught exception: [Error: Callback was already called.]
[2021-02-12T06:01:08.173Z] error: Error: Callback was already called.
    at /home/smk762/komodo-install-explorer/komodo-explorer/node_modules/bitcore-node-komodo/node_modules/async/lib/async.js:43:36
    at /home/smk762/komodo-install-explorer/komodo-explorer/node_modules/bitcore-node-komodo/node_modules/async/lib/async.js:723:17
    at /home/smk762/komodo-install-explorer/komodo-explorer/node_modules/bitcore-node-komodo/node_modules/async/lib/async.js:167:37
    at /home/smk762/komodo-install-explorer/komodo-explorer/node_modules/bitcore-node-komodo/node_modules/async/lib/async.js:652:25
    at /home/smk762/komodo-install-explorer/komodo-explorer/node_modules/bitcore-node-komodo/lib/services/bitcoind.js:2258:32
    at IncomingMessage.<anonymous> (/home/smk762/komodo-install-explorer/komodo-explorer/node_modules/bitcore-node-komodo/node_modules/bitcoind-rpc/lib/index.js:91:9)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:923:12)
    at nextTickCallbackWith2Args (node.js:511:9)
[2021-02-12T06:01:08.173Z] info: Beginning shutdown
[2021-02-12T06:01:08.174Z] info: Stopping insight-ui-komodo

```

Might be a setting or something I need to tweak, strangely not an issue for most other addresses I checked.

**Comment by gaeacodes** [comment]
> tag the rewards as "Lost rewards", hyperlinked to info on why they didnt get the rewards like

will do this

> I was getting a crash for address RCyANUW2H5985zk8p6NHJfPyNBXnTVzGDh though.

yes, I was getting similar crashes because of sending too many RPC requests. so, changed async.parallel to async.series. now, such crashes are not happening. but, it still takes too long to display the data. maybe because my server has low thread count/RAM.

here it is: http://34.122.103.103:7775/address/RCyANUW2H5985zk8p6NHJfPyNBXnTVzGDh

I am already returning "not able to estimate rewards" if the address has too many transactions. Example: http://34.122.103.103:7775/address/RD47yEoA4VGriqjeiLdMVKnuE7x7xqFy9r

if you make a fresh installation of the explorer, the crash should go away

**Comment by gaeacodes** [comment]
@smk762 Displays potential lost rewards when rewards are not claimed and also added the link.

**Comment by smk762** [comment]
No more crash on `RCyANUW2H5985zk8p6NHJfPyNBXnTVzGDh`
"Lost reward" message sighted and link operational.

Looking good mate! 

I'm about ready to approve this, will give it a day or two for other reviewers to put another set of eyes over it and poke around a bit in case I missed something.

**Comment by gaeacodes** [comment]
@smk762 Any updates?

**Review by smk762 — APPROVED** [review]
Working on my side, and all requested tweaks applied. Thanks @gaeacodes

**Review by ca333 — APPROVED** [review]

**Comment by ca333** [comment]
excellent, reach out on discord ref. bounty - thank you @gaeacodes @smk762 @gcharang

**Comment by gaeacodes** [comment]
@smk762 @ca333 @DeckerSU @gcharang 

Thanks for testing,merging the PR and all the help.
Just a few points of clarification:
1.This PR doesn't deal with difference between smart chains and the KMD chain.If a smart chain explorer is launched using these changes the UI won't be optimal and all the extra computation in the api and bitcore-node is not needed.The best way to use these changes is to create patches like @DeckerSU had done for the intial submitted changes.Here is the link for intial changes: https://github.com/DeckerSU/komodo-explorers-install/tree/e1dc16bf1bc3479085863c55d3f4de0b3a268e0f/rewards 
2. Also,this line needs to be changed to Decker's repo after the PR for bitcore node is merged(https://github.com/gaeacodes/bitcore-node-komodo/blob/10b243cc1082c9669d28f62e419d12be12ea5619/lib/scaffold/create.js#L23).I am leaving it like this for now in case someone wants to test these changes from my repos.

**Comment by ca333** [comment]
@gaeacodes plz reopen PR on https://github.com/KomodoPlatform/insight-ui-komodo/tree/kmd-rewards - yes Decker gave me some good feedback. A few layers should be enhanced - i.e. differentiation between ACs and KMD - spam-protection/prevention ref. rpc interface requests, et cetera.

**Comment by ca333** [comment]
it will be nice to visualise the reward as a separate input @gaeacodes 

example: screenshot from Decker solution proposal

paste


Also - are you able to modify the rpc interface on the komodo side? What we need is adding additional information to the `getrawtransaction` response - one additional field with the pre-calc of the reward amount. It will prevent 'spamming' rpc interface as it is currently implemented.

special thanks to @DeckerSU for solution-design review

**Comment by gaeacodes** [comment]
> plz reopen PR on https://github.com/KomodoPlatform/insight-ui-komodo/tree/kmd-rewards
 
will do.

https://user-images.githubusercontent.com/10762374/109789845-08de3280-7c11-11eb-9fce-6cdc89ee141b.png

Will update this view in new PR.

>It will prevent 'spamming' rpc interface as it is currently implemented.

With the currently available RPC from komodod, the way I have implemented is the only way to have rewards claim data displayed. But, I agree implementing the reward amount as an output for getrawtransaction RPC  will decrease the number of requests and computation being done in the bitcore-node layer.

>are you able to modify the rpc interface on the komodo side?
 
I have some experience with the C programming language and almost none with C++ . But, I will take a look and let you know if I am able to do it.

cc: @ca333

**Pull request merged**
